name: Test_Git_Actions

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: "test-project"
  DOCKER_IMAGE_TAG: master-${{ github.sha }}

  SLACK_SUCCESS_COLOR: "good"
  SLACK_FAILED_COLOR: "danger"
  SLACK_ICON_EMOJI: ":bell:"
  SLACK_TITLE: ":closed_book: ${{ github.repository }}"
  DOCKLE_ERROR_LEVEL: "fatal" # "fatal" or "warn" or "info"

jobs:
  Run:
    name: Git Hub Action
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login gitHub registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: docker build -t ${DOCKER_IMAGE_NAME}/${DOCKER_IMAGE_TAG} ./
      - name: Run dockle
        id: dockle
        run: ./tools/dockle_scan.sh -f ${DOCKLE_ERROR_LEVEL}
      - name: notify slack of results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL:    "random"
          SLACK_USERNAME:   ${{ env.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ env.SLACK_ICON_EMOJI }}
          SLACK_COLOR:      ${{ env.SLACK_SUCCESS_COLOR }}
          SLACK_TITLE:      ":closed_book: Dockle Result"
          SLACK_MESSAGE:    ${{ env.DOCKLE_RESULT }}
      - name: notify slack of results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL:    "random"
          SLACK_USERNAME:   ${{ env.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ env.SLACK_ICON_EMOJI }}
          SLACK_COLOR:      ${{ env.SLACK_FAILED_COLOR }}
          SLACK_TITLE:      ":closed_book: Dockle Result"
          SLACK_MESSAGE:    ${{ env.DOCKLE_RESULT }}
