name: Test_Git_Actions

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: "test-project"
  VERSION: master-${{ github.sha }}

  SLACK_ICON_EMOJI: ":bell:"
  SLACK_MESSAGE: ":closed_book: ${{ github.repository }}"

jobs:
  ImageBuild:
    name: build docker image
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login gitHub registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/$DOCKER_IMAGE_NAME:$VERSION ./
      - name: push image to gitHub registry
        run: docker push docker.pkg.github.com/${{ github.repository }}/$DOCKER_IMAGE_NAME:$VERSION
      - name: notify slack of failure results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "danger"
          SLACK_TITLE: "failed to ImageBuild :boom:"
          SLACK_ICON_EMOJI: ${{ SLACK_ICON_EMOJI }}
          SLACK_MESSAGE: ${{ SLACK_MESSAGE }}
      - name: notify slack of succsess results
        uses: rtCamp/action-slack-notify@e17352f
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "good"
          SLACK_TITLE: "successfully ImageBuild :boom:"
          SLACK_ICON_EMOJI: ${{ SLACK_ICON_EMOJI }}
          SLACK_MESSAGE: ${{ SLACK_MESSAGE }}

  dockle:
    name: dockle scan
    runs-on: ubuntu-18.04
    needs: ImageBuild
    steps:
      - name: checkout
        uses: actions/checkout@v2