name: Test_Git_Actions

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: "test-project"
  DOCKER_IMAGE_TAG: master-${{ github.sha }}

  SLACK_SUCCESS_COLOR: "good"
  SLACK_FAILED_COLOR: "danger"
  SLACK_ICON_EMOJI: ":bell:"
  SLACK_TITLE: ":closed_book: ${{ github.repository }}"
  DOCKLE_ERROR_LEVEL: "warn" # "fatal" or "warn" or "info"

jobs:
  ImageBuild:
    name: build docker image
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login gitHub registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ./
      - name: notify slack of failure results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ env.SLACK_FAILED_COLOR }}
          SLACK_TITLE: ${{ env.SLACK_TITLE }}
          SLACK_ICON_EMOJI: ${{ env.SLACK_ICON_EMOJI }}
          SLACK_MESSAGE: "failed to build docker image"
      - name: push image to gitHub registry
        run: docker push docker.pkg.github.com/${{ github.repository }}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

  dockle:
    name: run dockle
    runs-on: ubuntu-18.04
    needs: ImageBuild
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login gitHub registry
        run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
      - name: pull image gitHub registry
        run: docker pull docker.pkg.github.com/${{ github.repository }}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      - name: Run dockle
        id: dockle
        run: |
          ScanResult=$(./tools/dockle_scan.sh \
            -e ${DOCKLE_ERROR_LEVEL} -t "docker.pkg.github.com/${{ github.repository }}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}")
          echo ::set-output name=result::$(echo ${ScanResult})
      - name: notify slack of results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK:    ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL:    "random"
          SLACK_USERNAME:   ${{ env.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ env.SLACK_ICON_EMOJI }}
          SLACK_COLOR:      "#1475dc"
          SLACK_TITLE:      ":closed_book: Dockle Result"
          SLACK_MESSAGE:    ${{ steps.dockle.outputs.result }}

  ImagePush:
    name: push docker image
    runs-on: ubuntu-18.04
    needs: [dockle]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: notify slack of failure results
        uses: rtCamp/action-slack-notify@e17352f
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ env.SLACK_FAILED_COLOR }}
          SLACK_TITLE: ${{ env.SLACK_TITLE }}
          SLACK_ICON_EMOJI: ${{ env.SLACK_ICON_EMOJI }}
          SLACK_MESSAGE: "failed to push to ECR"